  access_key_id: 'AKIAIFZ3F276D46QD6MQ'
  secret_access_key: '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'
  bucket: 'analive-s3bjs4i-1b1xr7pm0a64'
  s3_host_name: 's3-ap-northeast-1.amazonaws.com'
  s3_region: 'ap-northeast-1'
