  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  bucket: 'analive-s3bjs4i-1b1xr7pm0a64'
  s3_host_name: 's3-ap-northeast-1.amazonaws.com'
  s3_region: 'ap-northeast-1'
