# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1f4920b97c132b9ac607c32bc97901b0f5718d689be1390af213005ce2d36f05343f5ee4a44fa43378b34febd637b3b2c92dda48493f149dcdfb1954c77595f6

test:
  secret_key_base: 9e8a91cad39cffd5428854fabe463972d7776ca9aae744791585a06fdc2b96f86779232e105de37356416fd30a628f60557a843a5ff50781bb61cb621c42aebb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  DB_HOST: ad1ju88kjongy51.cddifxbcbfvp.ap-northeast-1.rds.amazonaws.com
  DB_NAME: AnaLive
  S3_BUCKET_NAME: analive-s3bjs4i-1b1xr7pm0a64
  AWS_REGION: ap-northeast-1
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
